### ISSUE TITLE
implement 'star/watch/follow project'

### ISSUE THREAD

**Issue by elf-pavlik** [ralexrdz/vientos#10]
user looking at project page should see button to 'follow' it

### TODO
* [x] /user/follows POST to add new follow
  * [ ] verify if not already following
* [x] /user/follows/{id} DELETE to remove particular following
